version: '3.8'

networks:
  estore:
    driver: bridge

services:
  server:
    image: "nginx:1.21.6-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./:/code/ecommerce
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - estore
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
    ports:
      - "9001:9000"
    volumes:
      - ./:/code/ecommerce
    networks:
      - estore
    depends_on:
      - postgres
  postgres:
    build:
      context: ./
      dockerfile: .docker/postgres/Dockerfile
      args:
        - VERSION=latest
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.docker/volumes/postgres:/var/lib/postgresql/data
      - ./.docker/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
      - ./.docker/postgres/postgres.conf:/data/postgres/postgresql.conf
    ports:
      - "5454:5432"
    networks:
      - estore
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./.docker/volumes/redis:/data
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7379:6379"
    networks:
      - estore
